# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Can't find python right now
    # config.vm.provision "shell", path: "scripts/provision.sh"
    config.vm.define "7" do |vmconfig|
        # vmconfig.vm.provision "ansible" do |ansible|
        #     ansible.playbook = "playbooks/inventory.yml"
        # end
        vmconfig.vm.box = "generic/openbsd7"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            override.vm.box = "generic/openbsd7"
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end

        vmconfig.vm.provider "qemu" do |qemu, override|
            override.vm.box = "generic/openbsd7"
            qemu.machine = "virt,accel=tcg,highmem=off"
            qemu.memory = "1G"
            qemu.cpu = "qemu64"
            qemu.smp = "1" # Simulated CPU's
            qemu.arch = "x86_64"
            qemu.qemu_dir = "/usr/share/qemu"
            qemu.machine = "q35"
            qemu.net_device = "socket"
        end
    end

end
