# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    #config.vm.provision "shell", path: "provision.sh"

    config.vm.define "12" do |vmconfig|
        #vmconfig.vm.provision "shell", path: "provision.sh"
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/inventory.yml"
        end
        vmconfig.vm.box = "debian/bookworm64"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            override.vm.box = "generic-x64/debian12"
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end

        vmconfig.vm.provider "qemu" do |qemu, override|
            override.vm.box = "generic/debian12"
            qemu.machine = "virt,accel=tcg,highmem=off"
            qemu.memory = "1G"
            qemu.cpu = "qemu64"
            qemu.smp = "1" # Simulated CPU's
            qemu.arch = "x86_64"
            qemu.qemu_dir = "/usr/share/qemu"
            qemu.machine = "q35"
            qemu.net_device = "socket"
        end
        # vmconfig.vm.network "private_network", type: "dhcp"#, hostname: true
        # vmconfig.vm.hostname = "bookworm.local"
        #vmconfig.vm.network "public_network", ip: "10.20.20.1", hostname: true
    end

    config.vm.define "12docker" do |vmconfig|
        #vmconfig.vm.provision "shell", path: "provision.sh"
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/docker.yml"
        end
        vmconfig.vm.box = "generic-x64/debian12"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            override.vm.box = "generic/debian12"
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end

        vmconfig.vm.provider "qemu" do |qemu, override|
            override.vm.box = "generic/debian12"
            qemu.machine = "virt,accel=tcg,highmem=off"
            qemu.memory = "1G"
            qemu.cpu = "qemu64"
            qemu.smp = "1" # Simulated CPU's
            qemu.arch = "x86_64"
            qemu.qemu_dir = "/usr/share/qemu"
            qemu.machine = "q35"
            qemu.net_device = "socket"
        end
        # vmconfig.vm.network "private_network", type: "dhcp"#, hostname: true
        # vmconfig.vm.hostname = "bookworm.local"
        #vmconfig.vm.network "public_network", ip: "10.20.20.1", hostname: true
    end
    config.vm.define "9" do |vmconfig|
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/inventory.yml"
        end
        vmconfig.vm.box = "generic-x64/debian9"
        # vmconfig.vm.box_architecture = "amd64"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            override.vm.box = "generic/debian12"
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end

        vmconfig.vm.provider "qemu" do |qemu, override|
            override.vm.box = "generic/debian12"
            qemu.machine = "virt,accel=tcg,highmem=off"
            qemu.memory = "1G"
            qemu.cpu = "qemu64"
            qemu.smp = "1" # Simulated CPU's
            qemu.arch = "x86_64"
            qemu.qemu_dir = "/usr/share/qemu"
            qemu.machine = "q35"
            qemu.net_device = "socket"
        end
    end
    config.vm.define "10" do |vmconfig|
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/inventory.yml"
        end
        vmconfig.vm.box = "generic-x64/debian10"
        # Architecture may need to be set, but doesn't work with vagrant 2.3.7
        # vmconfig.vm.box_architecture = "amd64"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            override.vm.box = "generic/debian12"
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end

        vmconfig.vm.provider "qemu" do |qemu, override|
            override.vm.box = "generic/debian12"
            qemu.machine = "virt,accel=tcg,highmem=off"
            qemu.memory = "1G"
            qemu.cpu = "qemu64"
            qemu.smp = "1" # Simulated CPU's
            qemu.arch = "x86_64"
            qemu.qemu_dir = "/usr/share/qemu"
            qemu.machine = "q35"
            qemu.net_device = "socket"
        end
    end
    config.vm.define "11" do |vmconfig|
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/inventory.yml"
        end
        vmconfig.vm.box = "generic-x64/debian11"
        # vmconfig.vm.box_architecture = "amd64"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1024
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
        vmconfig.vm.provider "vmware_desktop" do |vmware, override|
            override.vm.box = "generic/debian12"
            vmware.vmx["memsize"] = "1024"
            vmware.vmx["numvcpus"] = "1"
        end

        vmconfig.vm.provider "qemu" do |qemu, override|
            override.vm.box = "generic/debian12"
            qemu.machine = "virt,accel=tcg,highmem=off"
            qemu.memory = "1G"
            qemu.cpu = "qemu64"
            qemu.smp = "1" # Simulated CPU's
            qemu.arch = "x86_64"
            qemu.qemu_dir = "/usr/share/qemu"
            qemu.machine = "q35"
            qemu.net_device = "socket"
        end
    end

    config.vm.define "kali" do |vmconfig|
        vmconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/inventory.yml"
        end
        vmconfig.vm.box = "kalilinux/rolling"
        # Architecture may need to be set, but doesn't work with vagrant 2.3.7
        # vmconfig.vm.box_architecture = "amd64"
        vmconfig.vm.provider "libvirt" do |libvirt|
            libvirt.driver = "kvm"
            libvirt.memory = 1200
            libvirt.cpus = 2
            libvirt.video_type = "virtio"
            #libvirt.graphics_type = "vnc"
        end
        vmconfig.vm.provider "virtualbox" do |virtualbox,override|
            virtualbox.memory = 1024
            virtualbox.cpus = 1
            #override.vm.network "private_network", ip: "192.168.56.4"
        end
    end
end
